# Generated by Django 2.1.3 on 2018-11-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181111_1810'),
        ('members', '0003_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
