# Generated by Django 2.1.4 on 2018-12-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181209_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_html',
            field=models.TextField(blank=True, verbose_name='태그가 HTML화 된 댓글 내용'),
        ),
    ]
